# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('body', models.TextField()),
                ('url_body', models.CharField(blank=True, max_length=200)),
                ('type', models.IntegerField(blank=True)),
            ],
        ),
    ]
