# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20170604_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymessage',
            name='talk_direction',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
