# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_auto_20170604_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('body', models.CharField(max_length=1024)),
            ],
        ),
    ]
